### PR TITLE
Added Neha Folder

### PR DESCRIPTION
**Pull request by Neha152001**
I have added my web page to the student portfolio

### CODE REVIEW

**Comment by dntandan** [comment]
@Neha152001 please change you folder name to @username of your GitHub . For example, look at the folder name of mine.

**Comment by Neha152001** [comment]
> @Neha152001 please change you folder name to @username of your GitHub . For example, look at the folder name of mine.

Okay

**Comment by dntandan** [comment]
@Neha152001 also you forgot to add your project link to index.html page in the root directory. add that also.

**Comment by dntandan** [comment]
@Neha152001 Looks like you have directly made a commit to the main repo instead of your forked repo and adding that in PR.   
  
I will merge this PR now but keep in mind that you don't have to make commits on the main repo although you have the write access to it. Always follow the contribution guideline mentioned in the readme of the project.

**Review by dntandan — COMMENTED** [review]
LGTM now

**Comment by Neha152001** [comment]
> @Neha152001 Looks like you have directly made a commit to the main repo instead of your forked repo and adding that in PR. 
> 
> I will merge this PR now but keep in mind that you don't have to make commits on the main repo although you have the write access to it. Always follow the contribution guideline mentioned in the readme of the project.

Sorry that was by mistake will keep this in mind

**Pull request merged**
